### ISSUE TITLE
Request received is not a websocket request - Xamarin.iOS

### ISSUE THREAD

**Issue by HealsCodes** [maxfridbe/websocketextensions#1]
Not sure if it’s an underlying issue with Microsoft’s WebSocket or a configuration issue but if I use your package to start a WebSockerServer inside of a Xamarin.iOS application any request to connect to said server fails with the this message.

Ich cross referenced your code and it seems that for some reason `IsWebSocketRequest` is always false despite being on the latest Xamarin.iOS version.

Given the NuGet package is available on this platform I had hoped it would allow me to run a server too.

**Comment by maxfridbe** [comment]
I have done no testing in Xamarin, however the tests I have run in NET Core 2.1. (not sure if there is a microsoft specific implementation difference there), If you could reproduce the issue in a test I would be happy to try to fix.
Relevant test:
 ```
[Fact]
        public async Task TestCreateServer_connect_recv_text()
        {
            //arrange
            var server = new WebSocketServer();
            string data = null;
            var port = _FreeTcpPort();

            Action<StringMessageReceivedEventArgs> handler = (s) => data = s.Data;

            server.AddRouteBehavior("/aaa", () => new testBeh() { StringMessageHandler = handler });
            await server.StartAsync($"http://localhost:{port}/");

            var client = new ClientWebSocket();
            await client.ConnectAsync(new Uri($"ws://localhost:{port}/aaa"), CancellationToken.None);


            //act
            await client.SendAsync(new ArraySegment<byte>(Encoding.UTF8.GetBytes("hi")), WebSocketMessageType.Text, true, CancellationToken.None);

            await Task.Delay(100);

            //assert
            Assert.Equal("hi", data);

        }
```

**Comment by maxfridbe** [comment]
I have not had a chance to try this but, i have split the server into WebListenerWebSocketServer and HttpListenerWebSocketServer.  WebListener is the dotcore way so im hoping this will work, reopen if you get a chance to try.
