### ISSUE TITLE
OnStringMessage event objects is missing clientID

### ISSUE THREAD

**Issue by envis10n** [maxfridbe/websocketextensions#5]
The client ID on the object provided to the handler in the behavior contains an empty Client ID field (empty string)

**Comment by maxfridbe** [comment]
In the latest 2.1.0.0, I have done away with clientid, and it is all ConnectionId, which is never null.  To correlate a clientid with a connection id you can keep a dictionary from the OnClientConnected() handler which will raise the client id and connectionid , that way multiple clients can be connected, but websocket extensions no longer has to manage string clientids.
