### ISSUE TITLE
Server can't run in Unix through libmono (HTTP.sys)

### ISSUE THREAD

**Issue by arommelaere** [maxfridbe/websocketextensions#7]
I am trying to run a websocket server using websocketextensions on unix via libmono,
However seems it's using HTTP.sys which is not compatible with unix (https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/httpsys?view=aspnetcore-6.0)

```
HTTP.sys is a web server for ASP.NET Core that only runs on Windows. HTTP.sys is an alternative to Kestrel server and offers some features that Kestrel doesn't provide.
```

![image](https://user-images.githubusercontent.com/1508444/141605400-a2af065d-e95a-4974-8327-f5ea5b6fb611.png)

https://stackoverflow.com/questions/54234872/how-to-fix-unable-to-load-shared-library-httpapi-dll-or-one-of-its-dependenci

Is it possible to make it compatible with unix somehow ?

The solution from my understanding, would be to use Kestrel instead:
https://docs.microsoft.com/en-us/aspnet/core/fundamentals/servers/kestrel?view=aspnetcore-6.0
```
Kestrel is supported on all platforms and versions that .NET Core supports.
```

**Comment by maxfridbe** [comment]
.Kestrel nuget package now exists as a host works in production linux
